t = open('app/templates/authentication/11-3.admin/11-3-3.setting/1.setting.html', encoding='utf-8').read()
sms = t.find('id="sms-settings-card"')
cotp = t.find('id="company-otp-settings-card"')
cp = t.find('id="code-policy-card"')
print('SMS idx:', sms, ' / COTP idx:', cotp, ' / CP idx:', cp)
print('Order OK' if sms < cotp < cp else 'ORDER WRONG')
print('CSS v1.0.33:', 'v=1.0.33' in t)
print('JS 20260419b:', '20260419b"' in t)
print('settings-col-stack opens:', t.count('<div class="settings-col-stack">'))
print('settings-col-stack closes (approx):', t.count('</div>'))
