"""drop portal_users table

Revision ID: 0ecb312eb858
Revises: f0e896d71cd4
Create Date: 2025-11-12 00:55:32.522330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb312eb858'
down_revision = 'f0e896d71cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_portal_users_login_id'))
        batch_op.drop_index(batch_op.f('ix_portal_users_role'))
        batch_op.drop_index(batch_op.f('ix_portal_users_status'))

    op.drop_table('portal_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('login_fail_cnt', sa.INTEGER(), nullable=True),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_login_id'), ['login_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_portal_users_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###
