"""add last_terms_accepted_at to auth_users

Revision ID: 7cc76439a2c4
Revises: 0ecb312eb858
Create Date: 2025-11-12 06:41:54.363484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc76439a2c4'
down_revision = '0ecb312eb858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_users', schema=None) as batch_op:
        batch_op.drop_column('last_terms_accepted_at')

    # ### end Alembic commands ###
