"""add fk and status indexes

Revision ID: a2f537df1c01
Revises: 57840fa18db8
Create Date: 2025-11-11 06:31:44.631091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f537df1c01'
down_revision = '57840fa18db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_login_history_emp_no'), ['emp_no'], unique=False)

    with op.batch_alter_table('auth_password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_password_history_emp_no'), ['emp_no'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_status'), ['status'], unique=False)

    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_networks_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_networks_status'), ['status'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_status'), ['status'], unique=False)

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_software_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_status'), ['status'], unique=False)

    with op.batch_alter_table('storages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storages_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storages_status'), ['status'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    with op.batch_alter_table('storages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storages_status'))
        batch_op.drop_index(batch_op.f('ix_storages_company_id'))

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_status'))
        batch_op.drop_index(batch_op.f('ix_software_company_id'))

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_status'))
        batch_op.drop_index(batch_op.f('ix_servers_company_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_company_id'))

    with op.batch_alter_table('networks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_networks_status'))
        batch_op.drop_index(batch_op.f('ix_networks_company_id'))

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_company_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    with op.batch_alter_table('auth_password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_password_history_emp_no'))

    with op.batch_alter_table('auth_login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_login_history_emp_no'))

    # ### end Alembic commands ###
