"""add portal_users table

Revision ID: f0e896d71cd4
Revises: a2f537df1c01
Create Date: 2025-11-12 00:47:33.489802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e896d71cd4'
down_revision = 'a2f537df1c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('login_fail_cnt', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_users_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_login_id'), ['login_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_portal_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_portal_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portal_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_users_status'))
        batch_op.drop_index(batch_op.f('ix_portal_users_role'))
        batch_op.drop_index(batch_op.f('ix_portal_users_login_id'))
        batch_op.drop_index(batch_op.f('ix_portal_users_employee_id'))

    op.drop_table('portal_users')
    # ### end Alembic commands ###
